# OpenSees Geometry DATA File - Generated by CSF
# Beam Span: 10.000000 (units follow your model)
# Stations: 10
# NOTE: This file is meant to be PARSED AS DATA (do NOT source it as Tcl).
# NOTE: Section lines append 'Cx Cy' as CSF-only fields (not OpenSees syntax).
#
# CSF_EXPORT_MODE: E=E_ref ; A/I/J are station-wise CSF results (already weighted)
# CSF_TORSION_SELECTION: J_tors = (J_sv_wall>0) else (J_sv_cell>0) else (J>0) else ERROR

# CSF_Z_STATIONS: 0 0.402330459168 1.30613067447 2.61037525095 4.17360521167 5.82639478833 7.38962474905 8.69386932553 9.59766954083 10

# Informational nodes (best-fit line through centroid offsets)
node 1 0 1.35332593178e-17 0
node 2 0 0.25 10

geomTransf Linear 1 1 0 0

section Elastic 1 1.000000e+00 3.600000e-01 4.320000e-02 2.700000e-03 5.000000e-01 4.590000e-02 0.000000e+00 0.000000e+00  # torsion=LEGACY
section Elastic 2 1.000000e+00 3.539650e-01 4.106363e-02 2.654738e-03 5.000000e-01 4.371837e-02 0.000000e+00 1.005826e-02  # torsion=LEGACY
section Elastic 3 1.000000e+00 3.404080e-01 3.652378e-02 2.553060e-03 5.000000e-01 3.907684e-02 0.000000e+00 3.265327e-02  # torsion=LEGACY
section Elastic 4 1.000000e+00 3.208444e-01 3.058155e-02 2.406333e-03 5.000000e-01 3.298788e-02 0.000000e+00 6.525938e-02  # torsion=LEGACY
section Elastic 5 1.000000e+00 2.973959e-01 2.435462e-02 2.230469e-03 5.000000e-01 2.658508e-02 0.000000e+00 1.043401e-01  # torsion=LEGACY
section Elastic 6 1.000000e+00 2.726041e-01 1.875743e-02 2.044531e-03 5.000000e-01 2.080196e-02 0.000000e+00 1.456599e-01  # torsion=LEGACY
section Elastic 7 1.000000e+00 2.491556e-01 1.432149e-02 1.868667e-03 5.000000e-01 1.619016e-02 0.000000e+00 1.847406e-01  # torsion=LEGACY
section Elastic 8 1.000000e+00 2.295920e-01 1.120589e-02 1.721940e-03 5.000000e-01 1.292783e-02 0.000000e+00 2.173467e-01  # torsion=LEGACY
section Elastic 9 1.000000e+00 2.160350e-01 9.335731e-03 1.620262e-03 5.000000e-01 1.095599e-02 0.000000e+00 2.399417e-01  # torsion=LEGACY
section Elastic 10 1.000000e+00 2.100000e-01 8.575000e-03 1.575000e-03 5.000000e-01 1.015000e-02 0.000000e+00 2.500000e-01  # torsion=LEGACY
