#!/usr/bin/env python3
"""
Generate a minimal OpenFAST / ElastoDyn structural-only case around an existing
ElastoDyn tower file generated from CSF.

Outputs:
  - Main.fst
  - ElastoDyn.dat
  - ElastoDyn_Blade.dat

The tower file itself is not regenerated here. It is referenced directly by the
ElastoDyn primary input file.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Tuple

import yaml


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate minimal OpenFAST case templates around an existing ElastoDyn tower file.")
    p.add_argument("tower_file", help="Existing ElastoDyn tower file, e.g. histwin_tower_ElastoDyn_Tower.dat")
    p.add_argument("--yaml", dest="yaml_file", default=None, help="CSF YAML file to infer tower height (default: try <stem>.yaml)")
    p.add_argument("--outdir", default=".", help="Output directory for generated files")
    p.add_argument("--fst-name", default="Main.fst", help="Main OpenFAST input filename")
    p.add_argument("--ed-name", default="ElastoDyn.dat", help="ElastoDyn primary input filename")
    p.add_argument("--blade-name", default="ElastoDyn_Blade.dat", help="ElastoDyn blade input filename")
    return p.parse_args()


def infer_yaml_path(tower_file: Path, yaml_arg: str | None) -> Path | None:
    if yaml_arg:
        yp = Path(yaml_arg)
        return yp if yp.exists() else None
    stem = tower_file.name
    suffix = "_ElastoDyn_Tower.dat"
    if stem.endswith(suffix):
        candidate = tower_file.with_name(stem[:-len(suffix)] + ".yaml")
        if candidate.exists():
            return candidate
    return None


def read_tower_height(yaml_file: Path) -> Tuple[float, float, float]:
    with open(yaml_file, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    z0 = float(data["CSF"]["sections"]["S0"]["z"])
    z1 = float(data["CSF"]["sections"]["S1"]["z"])
    return z0, z1, z1 - z0


def write_main_fst(path: Path, ed_name: str) -> None:
    text = f'''------- OpenFAST v3.x INPUT FILE -----------------------------------------------
Generated by generate_openfast_case_templates.py
---------------------- SIMULATION CONTROL --------------------------------------
False          Echo        - Echo input data to <RootName>.ech (flag)
"FATAL"        AbortLevel  - Error level when simulation should abort (string)
30             TMax        - Total run time (s)
0.01           DT          - Recommended module time step (s)
3              ModCoupling - Module coupling method (switch)
2              InterpOrder - Interpolation order for input/output time history (-)
0              NumCrctn    - Number of correction iterations (-)
0.0            RhoInf      - Numerical damping parameter (-)
1e-4           ConvTol     - Convergence iteration error tolerance (-)
6              MaxConvIter - Maximum number of convergence iterations (-)
1.5            DT_UJac     - Time between calls to get Jacobians (s)
1E+06          UJacSclFact - Scaling factor used in Jacobians (-)
---------------------- FEATURE SWITCHES AND FLAGS ------------------------------
1              NRotors     - Number of rotors in turbine (-)
1              CompElast   - Compute structural dynamics (1=ElastoDyn)
0              CompInflow  - Compute inflow wind velocities (0=None)
0              CompAero    - Compute aerodynamic loads (0=None)
0              CompServo   - Compute control and electrical-drive dynamics (0=None)
0              CompSeaSt   - Compute sea state information (0=None)
0              CompHydro   - Compute hydrodynamic loads (0=None)
0              CompSub     - Compute sub-structural dynamics (0=None)
0              CompMooring - Compute mooring system (0=None)
0              CompIce     - Compute ice loads (0=None)
0              CompSoil    - Compute soil-structural dynamics (0=None)
0              MHK         - MHK turbine type (0=Not an MHK turbine)
False          MirrorRotor - Flag to reverse rotor rotation direction
---------------------- ENVIRONMENTAL CONDITIONS --------------------------------
9.80665        Gravity     - Gravitational acceleration (m/s^2)
1.225          AirDens     - Air density (kg/m^3)
0              WtrDens     - Water density (kg/m^3)
1.464e-05      KinVisc     - Kinematic viscosity (m^2/s)
335            SpdSound    - Speed of sound (m/s)
103500         Patm        - Atmospheric pressure (Pa)
1700           Pvap        - Vapour pressure (Pa)
0              WtrDpth     - Water depth (m)
0              MSL2SWL     - Offset between still-water level and mean sea level (m)
---------------------- INPUT FILES ---------------------------------------------
"{ed_name}"    EDFile      - Name of file containing ElastoDyn input parameters
"unused"       BDBldFile(1)- BeamDyn blade file 1
"unused"       BDBldFile(2)- BeamDyn blade file 2
"unused"       BDBldFile(3)- BeamDyn blade file 3
"unused"       InflowFile  - Name of file containing inflow wind input parameters
"unused"       AeroFile    - Name of file containing aerodynamic input parameters
"unused"       ServoFile   - Name of file containing control and electrical-drive input parameters
"unused"       SeaStFile   - Name of file containing sea state input parameters
"unused"       HydroFile   - Name of file containing hydrodynamic input parameters
"unused"       SubFile     - Name of file containing sub-structural input parameters
"unused"       MooringFile - Name of file containing mooring system input parameters
"unused"       IceFile     - Name of file containing ice input parameters
"unused"       SoilFile    - Name of file containing soil-structural input parameters
---------------------- OUTPUT --------------------------------------------------
True           SumPrint    - Print summary data to <RootName>.sum (flag)
1              SttsTime    - Amount of time between screen status messages (s)
99999          ChkptTime   - Amount of time between creating checkpoint files (s)
0.05           DT_Out      - Time step for tabular output (s)
0              TStart      - Time to begin tabular output (s)
3              OutFileFmt  - Format for tabular output file (1=.out,2=.outb,3=both)
True           TabDelim    - Use tab delimiters in text tabular output file? (flag)
"G0"           OutFmt      - Format used for text tabular output, excluding time channel
---------------------- LINEARIZATION -------------------------------------------
False          Linearize   - Linearization analysis (flag)
False          CalcSteady  - Calculate steady-state periodic operating point? (flag)
3              TrimCase    - Controller parameter to be trimmed (-)
0.001          TrimTol     - Tolerance for rotational speed convergence (-)
0.01           TrimGain    - Proportional gain for rotational speed error
0              Twr_Kdmp    - Damping factor for tower (unused here)
0              Bld_Kdmp    - Damping factor for blades (unused here)
1              NLinTimes   - Number of times to linearize (-)
0              LinTimes    - List of times at which to linearize (s)
1              LinInputs   - Inputs included in linearization (switch)
1              LinOutputs  - Outputs included in linearization (switch)
False          LinOutJac   - Include full Jacobians in linearization output? (flag)
False          LinOutMod   - Write module-level linearization output files? (flag)
---------------------- VISUALIZATION -------------------------------------------
0              WrVTK       - VTK visualization data output (0=None)
1              VTK_type    - Type of VTK visualization data
False          VTK_fields  - Write mesh fields to VTK data files? (flag)
15             VTK_fps     - Frame rate for VTK output (fps)
'''
    path.write_text(text, encoding="utf-8")


def write_elastodyn(path: Path, blade_name: str, tower_name: str, tower_height: float) -> None:
    text = f'''------- ELASTODYN v3.x INPUT FILE ----------------------------------------------
Generated by generate_openfast_case_templates.py
---------------------- SIMULATION CONTROL --------------------------------------
False          Echo        - Echo input data to <RootName>.ech (flag)
3              Method      - Integration method (3=ABM4)
"default"      DT          - Integration time step (s)
---------------------- DEGREES OF FREEDOM --------------------------------------
False          FlapDOF1    - First flapwise blade mode DOF (flag)
False          FlapDOF2    - Second flapwise blade mode DOF (flag)
False          EdgeDOF     - First edgewise blade mode DOF (flag)
False          PitchDOF    - Blade pitch DOF (flag)
False          TeetDOF     - Rotor-teeter DOF (flag)
False          DrTrDOF     - Drivetrain rotational-flexibility DOF (flag)
False          GenDOF      - Generator DOF (flag)
False          YawDOF      - Yaw DOF (flag)
True           TwFADOF1    - First fore-aft tower bending-mode DOF (flag)
True           TwFADOF2    - Second fore-aft tower bending-mode DOF (flag)
True           TwSSDOF1    - First side-to-side tower bending-mode DOF (flag)
True           TwSSDOF2    - Second side-to-side tower bending-mode DOF (flag)
False          PtfmSgDOF   - Platform surge DOF (flag)
False          PtfmSwDOF   - Platform sway DOF (flag)
False          PtfmHvDOF   - Platform heave DOF (flag)
False          PtfmRDOF    - Platform roll DOF (flag)
False          PtfmPDOF    - Platform pitch DOF (flag)
False          PtfmYDOF    - Platform yaw DOF (flag)
---------------------- INITIAL CONDITIONS --------------------------------------
0              OoPDefl     - Initial out-of-plane blade-tip displacement (m)
0              IPDefl      - Initial in-plane blade-tip deflection (m)
0              BlPitch(1)  - Blade 1 initial pitch (deg)
0              BlPitch(2)  - Blade 2 initial pitch (deg)
0              BlPitch(3)  - Blade 3 initial pitch (deg)
0              TeetDefl    - Initial teeter angle (deg)
0              Azimuth     - Initial azimuth angle for blade 1 (deg)
0              RotSpeed    - Initial rotor speed (rpm)
0              NacYaw      - Initial nacelle-yaw angle (deg)
0              TTDspFA     - Initial fore-aft tower-top displacement (m)
0              TTDspSS     - Initial side-to-side tower-top displacement (m)
0              PtfmSurge   - Initial platform surge (m)
0              PtfmSway    - Initial platform sway (m)
0              PtfmHeave   - Initial platform heave (m)
0              PtfmRoll    - Initial platform roll (deg)
0              PtfmPitch   - Initial platform pitch (deg)
0              PtfmYaw     - Initial platform yaw (deg)
---------------------- TURBINE CONFIGURATION -----------------------------------
3              NumBl       - Number of blades (-)
63             TipRad      - Rotor apex to blade tip (m)
1.5            HubRad      - Rotor apex to blade root (m)
0              PreCone(1)  - Blade 1 cone angle (deg)
0              PreCone(2)  - Blade 2 cone angle (deg)
0              PreCone(3)  - Blade 3 cone angle (deg)
0              HubCM       - Distance from rotor apex to hub mass (m)
0              UndSling    - Undersling length (unused for 3 blades)
0              Delta3      - Delta-3 angle (unused for 3 blades)
0              AzimB1Up    - Azimuth value to use for I/O when blade 1 points up (deg)
-1.9           OverHang    - Distance from yaw axis to rotor apex (m)
1.75           ShftGagL    - Rotor apex to shaft strain gages (m)
-5             ShftTilt    - Shaft tilt angle (deg)
1.9            NacCMxn     - Downwind distance tower-top to nacelle CM (m)
0              NacCMyn     - Lateral distance tower-top to nacelle CM (m)
1.75           NacCMzn     - Vertical distance tower-top to nacelle CM (m)
-3.0           NcIMUxn     - Downwind distance tower-top to nacelle IMU (m)
0              NcIMUyn     - Lateral distance tower-top to nacelle IMU (m)
2.2            NcIMUzn     - Vertical distance tower-top to nacelle IMU (m)
1.96256        Twr2Shft    - Vertical distance tower-top to rotor shaft (m)
{tower_height:.5f}     TowerHt     - Tower height above ground level (m)
0              TowerBsHt   - Tower base height above ground level (m)
0              PtfmCMxt    - Platform CM x from ground/MSL (m)
0              PtfmCMyt    - Platform CM y from ground/MSL (m)
0              PtfmCMzt    - Platform CM z from ground/MSL (m)
0              PtfmRefxt   - Platform reference x from ground/MSL (m)
0              PtfmRefyt   - Platform reference y from ground/MSL (m)
0              PtfmRefzt   - Platform reference z from ground/MSL (m)
---------------------- MASS AND INERTIA ----------------------------------------
0              TipMass(1)  - Tip-brake mass, blade 1 (kg)
0              TipMass(2)  - Tip-brake mass, blade 2 (kg)
0              TipMass(3)  - Tip-brake mass, blade 3 (kg)
0              PBrIner(1)  - Pitch bearing inertia, blade 1 (kg m^2)
0              PBrIner(2)  - Pitch bearing inertia, blade 2 (kg m^2)
0              PBrIner(3)  - Pitch bearing inertia, blade 3 (kg m^2)
0              BlPIner(1)  - Blade pitch inertia, blade 1 (kg m^2)
0              BlPIner(2)  - Blade pitch inertia, blade 2 (kg m^2)
0              BlPIner(3)  - Blade pitch inertia, blade 3 (kg m^2)
56780          HubMass     - Hub mass (kg)
115926         HubIner     - Hub inertia about rotor axis (kg m^2)
0              HubIner_Teeter - Hub inertia about teeter axis (unused for 3 blades)
534.116        GenIner     - Generator inertia about HSS (kg m^2)
240000         NacMass     - Nacelle mass (kg)
2.60789E+06    NacYIner    - Nacelle inertia about yaw axis (kg m^2)
0              YawBrMass   - Yaw bearing mass (kg)
0              PtfmMass    - Platform mass (kg)
0              PtfmRIner   - Platform roll inertia about CM (kg m^2)
0              PtfmPIner   - Platform pitch inertia about CM (kg m^2)
0              PtfmYIner   - Platform yaw inertia about CM (kg m^2)
0              PtfmXYIner  - Platform xy moment of inertia about CM (kg m^2)
0              PtfmYZIner  - Platform yz moment of inertia about CM (kg m^2)
0              PtfmXZIner  - Platform xz moment of inertia about CM (kg m^2)
---------------------- BLADE ---------------------------------------------------
5              BldNodes    - Number of blade nodes used for analysis (-)
"{blade_name}" BldFile(1)  - Name of file containing properties for blade 1
"{blade_name}" BldFile(2)  - Name of file containing properties for blade 2
"{blade_name}" BldFile(3)  - Name of file containing properties for blade 3
---------------------- ROTOR-TEETER --------------------------------------------
0              TeetMod     - Rotor-teeter model (unused for 3 blades)
0              TeetDmpP    - Rotor-teeter damper position (deg)
0              TeetDmp     - Rotor-teeter damping constant (N-m/(rad/s))
0              TeetCDmp    - Coulomb damping moment (N-m)
0              TeetSStP    - Soft-stop position (deg)
0              TeetHStP    - Hard-stop position (deg)
0              TeetSSSp    - Soft-stop spring constant (N-m/rad)
0              TeetHSSp    - Hard-stop spring constant (N-m/rad)
---------------------- YAW-FRICTION --------------------------------------------
0              YawFrctMod  - Yaw-friction model (switch)
300            M_CSmax     - Maximum static Coulomb friction torque (N-m)
0              M_FCSmax    - Maximum static Coulomb friction torque proportional to shear force (N-m)
0              M_MCSmax    - Maximum static Coulomb friction torque proportional to bending moment (N-m)
40             M_CD        - Dynamic Coulomb friction moment (N-m)
0              M_FCD       - Dynamic Coulomb friction moment proportional to shear force (N-m)
0              M_MCD       - Dynamic Coulomb friction moment proportional to bending moment (N-m)
0              sig_v       - Linear viscous friction coefficient (N-m/(rad/s))
0              sig_v2      - Quadratic viscous friction coefficient (N-m/(rad/s)^2)
0              OmgCut      - Yaw angular velocity cutoff below which viscous friction is linearized (rad/s)
---------------------- DRIVETRAIN ----------------------------------------------
100            GBoxEff     - Gearbox efficiency (%)
97             GBRatio     - Gearbox ratio (-)
8.67637E+08    DTTorSpr    - Drivetrain torsional spring (N-m/rad)
6.215E+06      DTTorDmp    - Drivetrain torsional damper (N-m/(rad/s))
---------------------- FURLING -------------------------------------------------
False          Furling     - Read in additional model properties for furling turbine (flag)
"unused"       FurlFile    - Name of file containing furling properties
---------------------- TOWER ---------------------------------------------------
20             TwrNodes    - Number of tower nodes used for analysis (-)
"{tower_name}" TwrFile     - Name of file containing tower properties
---------------------- OUTPUT --------------------------------------------------
True           SumPrint    - Print summary data to <RootName>.sum (flag)
1              OutFile     - Output placement switch (-)
True           TabDelim    - Use tab delimiters in text tabular output file? (flag)
"G0"           OutFmt      - Format used for text tabular output (except time)
0              TStart      - Time to begin tabular output (s)
1              DecFact     - Decimation factor for tabular output (-)
0              NTwGages    - Number of tower nodes with strain gages (-)
0              TwrGagNd    - Tower gage nodes (unused)
0              NBlGages    - Number of blade nodes with strain gages (-)
0              BldGagNd    - Blade gage nodes (unused)
OutList        - The next line(s) contains a list of output parameters
"TTDspFA"
"TTDspSS"
"TwrBsMxt"
"TwrBsMyt"
"TwrBsMzt"
END
---------------------- NODE OUTPUTS --------------------------------------------
0              BldNd_BladesOut - Blades to output
99             BldNd_BlOutNd   - Blade nodes on each blade (unused)
OutListED      - The next line(s) contains a list of output parameters
END
'''
    path.write_text(text, encoding="utf-8")


def write_blade(path: Path) -> None:
    text = '''------- ELASTODYN V1.00.* INDIVIDUAL BLADE INPUT FILE --------------------------
Generated by generate_openfast_case_templates.py
---------------------- BLADE PARAMETERS ----------------------------------------
5              NBlInpSt    - Number of blade input stations (-)
0.477465       BldFlDmp(1) - Blade flap mode #1 structural damping (% of critical)
0.477465       BldFlDmp(2) - Blade flap mode #2 structural damping (% of critical)
0.477465       BldEdDmp(1) - Blade edge mode #1 structural damping (% of critical)
---------------------- BLADE ADJUSTMENT FACTORS --------------------------------
1              FlStTunr(1) - Blade flapwise modal stiffness tuner, 1st mode (-)
1              FlStTunr(2) - Blade flapwise modal stiffness tuner, 2nd mode (-)
1              AdjBlMs     - Factor to adjust blade mass density (-)
1              AdjFlSt     - Factor to adjust blade flap stiffness (-)
1              AdjEdSt     - Factor to adjust blade edge stiffness (-)
---------------------- DISTRIBUTED BLADE PROPERTIES ----------------------------
BlFract     StrcTwst   BMassDen    FlpStff     EdgStff
(-)         (deg)      (kg/m)      (N-m^2)     (N-m^2)
0.0000000   0.0000000  100.000000  1.00000E+08 1.00000E+08
0.2500000   0.0000000   90.000000  9.00000E+07 9.00000E+07
0.5000000   0.0000000   80.000000  8.00000E+07 8.00000E+07
0.7500000   0.0000000   70.000000  7.00000E+07 7.00000E+07
1.0000000   0.0000000   60.000000  6.00000E+07 6.00000E+07
---------------------- BLADE MODE SHAPES ---------------------------------------
0.8000         BldFl1Sh(2) - Flap mode 1, coeff of x^2
0.2000         BldFl1Sh(3) - Flap mode 1, coeff of x^3
0.0000         BldFl1Sh(4) - Flap mode 1, coeff of x^4
0.0000         BldFl1Sh(5) - Flap mode 1, coeff of x^5
0.0000         BldFl1Sh(6) - Flap mode 1, coeff of x^6
0.0000         BldFl2Sh(2) - Flap mode 2, coeff of x^2
1.0000         BldFl2Sh(3) - Flap mode 2, coeff of x^3
0.0000         BldFl2Sh(4) - Flap mode 2, coeff of x^4
0.0000         BldFl2Sh(5) - Flap mode 2, coeff of x^5
0.0000         BldFl2Sh(6) - Flap mode 2, coeff of x^6
0.8000         BldEdgSh(2) - Edge mode 1, coeff of x^2
0.2000         BldEdgSh(3) - Edge mode 1, coeff of x^3
0.0000         BldEdgSh(4) - Edge mode 1, coeff of x^4
0.0000         BldEdgSh(5) - Edge mode 1, coeff of x^5
0.0000         BldEdgSh(6) - Edge mode 1, coeff of x^6
'''
    path.write_text(text, encoding="utf-8")


def main() -> None:
    args = parse_args()
    tower_file = Path(args.tower_file).resolve()
    if not tower_file.exists():
        raise SystemExit(f"Tower file not found: {tower_file}")

    yaml_path = infer_yaml_path(tower_file, args.yaml_file)
    if yaml_path is not None:
        z0, z1, tower_height = read_tower_height(yaml_path)
    else:
        z0, z1, tower_height = 0.0, 0.0, 0.0

    outdir = Path(args.outdir).resolve()
    outdir.mkdir(parents=True, exist_ok=True)

    fst_path = outdir / args.fst_name
    ed_path = outdir / args.ed_name
    blade_path = outdir / args.blade_name

    write_main_fst(fst_path, args.ed_name)
    write_elastodyn(ed_path, args.blade_name, tower_file.name, tower_height)
    write_blade(blade_path)

    print(f"Generated: {fst_path}")
    print(f"Generated: {ed_path}")
    print(f"Generated: {blade_path}")
    if yaml_path is not None:
        print(f"Tower height inferred from YAML: z0={z0}, z1={z1}, H={tower_height}")
    else:
        print("WARNING: YAML not found. TowerHt left at 0.0 in ElastoDyn.dat; edit manually.")
    print("NOTE: non-CSF machine data remain the user's responsibility.")


if __name__ == "__main__":
    main()
