CSF_ACTIONS:
  stations:
    station_midle:
      - 30
    station_edge:
      - 0
      - 61.5
    stations_sparse:
      - 0
      - 25
      - 35
      - 45
      - 55
      - 61.5   
    stations_dense:
      - 2.8667
      - 19.95
      - 24.05
      - 28.15
      - 40.45
      - 44.55
      - 56.1667
      - 58.9
      - 61.5
  actions:  
    - volume:
          stations: station_edge
          output:
            - stdout
            - [out/j_sv_volume.csv,out/j_sv_volume.txt]   # optional; if omitted -> [stdout]
          params:
            n_points: 20           # optional (Gauss–Legendre points)
            fmt_display: ".6f"     # optional
            w_tol: 0.0             # optional; currently not used (kept for compatibility)
            
    - section_selected_analysis:
        stations: stations_dense
        output:
          - stdout
          - out/blade_selected.csv
          - out/blade_selected.txt
        #properties: [A, Cx, Cy, Ix, Iy, J_sv, J_s_vroark_fidelity]
        properties: [A, Cx, Cy, Ix, Iy,J]
        params:
          fmt_display: ".5g"         
         
                  
    - export_yaml:
        stations: station_edge
        output: out/exported_geometry.yaml
        
    - plot_section_2d:
        stations:
          - stations_sparse
        output:
          - [stdout,out/blade.bmp]
        show_ids: False
        show_vertex_ids: False
          
    - plot_volume_3d:
          params:
            line_percent: 30.0
            title: "Ruled volume"      
              
    - plot_properties:    
         output: [stdout,out/j_sv_properties.png]
         params: {num_points: 70}
         properties: [A, Ix, Iy,J]      

    - write_opensees_geometry:
        output: 
          - out/j_sv_geometry.tcl # required, file-only (no stdout)
        params:
          n_points: 10 # required int
          E_ref: 2.1e+11 # required float
          nu: 0.30 # required float          
  
#    - write_sap2000_geometry:
#        stations: stations_dense
#        output: [out/j_sv_sap2000_template_pack.txt]
#        params:
#          n_intervals: 7
#          material_name: "S355"
#          E_ref: 2.1e+11
#          nu: 0.30
#          mode: "BOTH"
#          include_plot: True
#          plot_filename: "out/j_sv_section_variation.png"


                             
        
