"""
csf_to_openfast.py  -  CSF geometry YAML -> OpenFAST minimal input files
without SubDyn, aligned to the r-test MinimalExample architecture.

Outputs:
    <stem>_ElastoDyn_Tower.dat
    <stem>_ElastoDyn.dat
    <stem>_ElastoDyn_Blade.dat
    <stem>_Main.fst

Requirements:  pip install csfpy pyyaml numpy
"""

from __future__ import annotations

VERSION = "1.3.0"

import argparse
import os
import subprocess
from pathlib import Path

import numpy as np
import yaml

from csf import section_full_analysis
from csf.io.csf_reader import CSFReader


# =============================================================================
# Step logger
# =============================================================================

def step(n: int, label: str) -> None:
    print(f"[csf_to_openfast v{VERSION}]  step {n}  -  {label}")


# =============================================================================
# CSF helpers
# =============================================================================

def load_csf(yaml_path: str):
    step(1, f"Loading CSF geometry from: {yaml_path}")
    read_result = CSFReader().read_file(yaml_path)
    field = read_result.field

    with open(yaml_path, encoding="utf-8") as f:
        data = yaml.safe_load(f)

    z0 = float(data["CSF"]["sections"]["S0"]["z"])
    z1 = float(data["CSF"]["sections"]["S1"]["z"])

    if read_result.issues:
        for issue in read_result.issues:
            print(f"  CSF issue: {issue.severity.value} {issue.code} - {issue.message}")

    print(f"  z range : {z0:.3f} -> {z1:.3f} m   H = {z1 - z0:.3f} m")
    return field, z0, z1


def compute_properties(field, z0: float, z1: float, n: int) -> list[dict]:
    step(2, f"Computing section properties at {n} stations via section_full_analysis")
    z_stations = np.linspace(z0, z1, n)
    results = []

    for z in z_stations:
        sa = section_full_analysis(field.section(float(z)))

        results.append({
            "z":  float(z),
            "A":  float(sa["A"]),
            "Ix": float(sa["Ix"]),
            "Iy": float(sa["Iy"]),
        })

    print(f"  A_base = {results[0]['A']:.6f} m2   A_top = {results[-1]['A']:.6f} m2")
    return results


# =============================================================================
# Writers
# =============================================================================

def write_elastodyn_tower(
    outfile: str,
    props: list[dict],
    z0: float,
    z1: float,
    E: float,
    rho: float,
    yaml_path: str,
) -> None:
    """Write ElastoDyn tower properties file.

    The file is parser-compatible with OpenFAST v5.x.
    Distributed properties are derived directly from CSF:
        TMassDen = rho * A
        TwFAStif = E * Ix
        TwSSStif = E * Iy

    Tower mode-shape coefficients are simple parser-valid placeholders.
    """
    step(3, f"Writing ElastoDyn tower: {outfile}")

    H = z1 - z0

    with open(outfile, "w", encoding="utf-8") as f:
        f.write("------- ELASTODYN V1.00.* TOWER INPUT FILE -------------------------------------\n")
        f.write(f"Generated by csf_to_openfast.py v{VERSION} from: {yaml_path}\n")

        f.write("---------------------- TOWER PARAMETERS ----------------------------------------\n")
        f.write(f"{len(props):11d}   NTwInpSt    - Number of input stations to specify tower geometry\n")
        f.write("        1.0   TwrFADmp(1) - Tower 1st fore-aft mode structural damping ratio (%)\n")
        f.write("        1.0   TwrFADmp(2) - Tower 2nd fore-aft mode structural damping ratio (%)\n")
        f.write("        1.0   TwrSSDmp(1) - Tower 1st side-to-side mode structural damping ratio (%)\n")
        f.write("        1.0   TwrSSDmp(2) - Tower 2nd side-to-side mode structural damping ratio (%)\n")

        f.write("---------------------- TOWER ADJUSTMENT FACTORS -------------------------------\n")
        f.write("          1   FAStTunr(1) - Tower fore-aft modal stiffness tuner, 1st mode (-)\n")
        f.write("          1   FAStTunr(2) - Tower fore-aft modal stiffness tuner, 2nd mode (-)\n")
        f.write("          1   SSStTunr(1) - Tower side-to-side stiffness tuner, 1st mode (-)\n")
        f.write("          1   SSStTunr(2) - Tower side-to-side stiffness tuner, 2nd mode (-)\n")
        f.write("          1   AdjTwMa     - Factor to adjust tower mass density (-)\n")
        f.write("          1   AdjFASt     - Factor to adjust tower fore-aft stiffness (-)\n")
        f.write("          1   AdjSSSt     - Factor to adjust tower side-to-side stiffness (-)\n")

        f.write("---------------------- DISTRIBUTED TOWER PROPERTIES ---------------------------\n")
        f.write("        HtFract                 TMassDen                 TwFAStif                 TwSSStif\n")
        f.write("          (-)                   (kg/m)                   (Nm^2)                   (Nm^2)\n")
        for p in props:
            hfrac = (p["z"] - z0) / H if H > 0.0 else 0.0
            mass_den = rho * p["A"]
            tw_fa = E * p["Ix"]
            tw_ss = E * p["Iy"]
            f.write(
                f"{hfrac:22.15E}  {mass_den:22.15E}  {tw_fa:22.15E}  {tw_ss:22.15E}\n"
            )

        f.write("---------------------- TOWER FORE-AFT MODE SHAPES -----------------------------\n")
        f.write("        1.0   TwFAM1Sh(2) - Mode 1, coefficient of x^2 term\n")
        f.write("        0.0   TwFAM1Sh(3) -         , coefficient of x^3 term\n")
        f.write("        0.0   TwFAM1Sh(4) -         , coefficient of x^4 term\n")
        f.write("        0.0   TwFAM1Sh(5) -         , coefficient of x^5 term\n")
        f.write("        0.0   TwFAM1Sh(6) -         , coefficient of x^6 term\n")
        f.write("        0.0   TwFAM2Sh(2) - Mode 2, coefficient of x^2 term\n")
        f.write("        0.0   TwFAM2Sh(3) -         , coefficient of x^3 term\n")
        f.write("        0.0   TwFAM2Sh(4) -         , coefficient of x^4 term\n")
        f.write("        0.0   TwFAM2Sh(5) -         , coefficient of x^5 term\n")
        f.write("        1.0   TwFAM2Sh(6) -         , coefficient of x^6 term\n")

        f.write("---------------------- TOWER SIDE-TO-SIDE MODE SHAPES ------------------------\n")
        f.write("        1.0   TwSSM1Sh(2) - Mode 1, coefficient of x^2 term\n")
        f.write("        0.0   TwSSM1Sh(3) -         , coefficient of x^3 term\n")
        f.write("        0.0   TwSSM1Sh(4) -         , coefficient of x^4 term\n")
        f.write("        0.0   TwSSM1Sh(5) -         , coefficient of x^5 term\n")
        f.write("        0.0   TwSSM1Sh(6) -         , coefficient of x^6 term\n")
        f.write("        0.0   TwSSM2Sh(2) - Mode 2, coefficient of x^2 term\n")
        f.write("        0.0   TwSSM2Sh(3) -         , coefficient of x^3 term\n")
        f.write("        0.0   TwSSM2Sh(4) -         , coefficient of x^4 term\n")
        f.write("        0.0   TwSSM2Sh(5) -         , coefficient of x^5 term\n")
        f.write("        1.0   TwSSM2Sh(6) -         , coefficient of x^6 term\n")

    print(f"  Tower file written with {len(props)} stations")
    print(f"  TMassDen base/top = {rho * props[0]['A']:.3f} / {rho * props[-1]['A']:.3f} kg/m")


def write_elastodyn_blade(outfile: str, hub_rad: float, yaml_path: str) -> None:
    """Write a dummy ElastoDyn blade file with template-compatible structure."""
    step(4, f"Writing dummy ElastoDyn blade: {outfile}")

    with open(outfile, "w", encoding="utf-8") as f:
        f.write("------- ELASTODYN V1.00.* INDIVIDUAL BLADE INPUT FILE --------------------------\n")
        f.write(f"Dummy blade generated by csf_to_openfast.py v{VERSION} from: {yaml_path}\n")

        f.write("---------------------- BLADE PARAMETERS ----------------------------------------\n")
        f.write("2              NBlInpSt    Number of blade input stations (-)\n")
        f.write("1.0            BldFlDmp(1) Blade 1st flapwise mode structural damping ratio (%)\n")
        f.write("1.0            BldFlDmp(2) Blade 2nd flapwise mode structural damping ratio (%)\n")
        f.write("1.0            BldEdDmp(1) Blade 1st edgewise mode structural damping ratio (%)\n")

        f.write("---------------------- BLADE ADJUSTMENT FACTORS --------------------------------\n")
        f.write("1.0            FlStTunr(1) Blade flapwise modal stiffness tuner, 1st mode (-)\n")
        f.write("1.0            FlStTunr(2) Blade flapwise modal stiffness tuner, 2nd mode (-)\n")
        f.write("1.0            AdjBlMs     Factor to adjust blade mass density (-)\n")
        f.write("1.0            AdjFlSt     Factor to adjust blade flap stiffness (-)\n")
        f.write("1.0            AdjEdSt     Factor to adjust blade edge stiffness (-)\n")

        f.write("---------------------- DISTRIBUTED BLADE PROPERTIES ----------------------------\n")
        f.write(f"{'BlFract':>14} {'StrcTwst':>14} {'BMassDen':>14} {'FlpStff':>14} {'EdgStff':>14}\n")
        f.write(f"{'(-)':>14} {'(deg)':>14} {'(kg/m)':>14} {'(Nm^2)':>14} {'(Nm^2)':>14}\n")
        f.write(f"{0.0:>14.7E} {0.0:>14.7E} {1.0:>14.7E} {1.0e6:>14.7E} {1.0e6:>14.7E}\n")
        f.write(f"{1.0:>14.7E} {0.0:>14.7E} {1.0:>14.7E} {1.0e6:>14.7E} {1.0e6:>14.7E}\n")

        f.write("---------------------- BLADE MODE SHAPES ---------------------------------------\n")
        f.write("1.0            BldFl1Sh(2)  Flap mode 1, coeff of x^2\n")
        f.write("0.0            BldFl1Sh(3)  Flap mode 1, coeff of x^3\n")
        f.write("0.0            BldFl1Sh(4)  Flap mode 1, coeff of x^4\n")
        f.write("0.0            BldFl1Sh(5)  Flap mode 1, coeff of x^5\n")
        f.write("0.0            BldFl1Sh(6)  Flap mode 1, coeff of x^6\n")
        f.write("0.0            BldFl2Sh(2)  Flap mode 2, coeff of x^2\n")
        f.write("0.0            BldFl2Sh(3)  Flap mode 2, coeff of x^3\n")
        f.write("0.0            BldFl2Sh(4)  Flap mode 2, coeff of x^4\n")
        f.write("0.0            BldFl2Sh(5)  Flap mode 2, coeff of x^5\n")
        f.write("1.0            BldFl2Sh(6)  Flap mode 2, coeff of x^6\n")
        f.write("0.0            BldEdgSh(2)  Edge mode 1, coeff of x^2\n")
        f.write("0.0            BldEdgSh(3)  Edge mode 1, coeff of x^3\n")
        f.write("0.0            BldEdgSh(4)  Edge mode 1, coeff of x^4\n")
        f.write("0.0            BldEdgSh(5)  Edge mode 1, coeff of x^5\n")
        f.write("1.0            BldEdgSh(6)  Edge mode 1, coeff of x^6\n")

    print(f"  Dummy blade: template-compatible format, 2 stations, HubRad = {hub_rad:.3f} m")


def write_elastodyn(
    outfile: str,
    twr_file: str,
    blade_file: str,
    z0: float,
    z1: float,
    rna: dict,
    yaml_path: str,
) -> None:
    """Write ElastoDyn.dat aligned to MinimalExample architecture."""
    step(5, f"Writing ElastoDyn input: {outfile}")

    H        = z1 - z0
    twr_name = os.path.basename(twr_file)
    bld_name = os.path.basename(blade_file)
    tip_rad  = rna["hub_rad"] + 1.0

    def w(fh, value: str, label: str, desc: str) -> None:
        fh.write(f"{value:<16} {label:<14} - {desc}\n")

    with open(outfile, "w", encoding="utf-8") as f:
        f.write("------- ELASTODYN v1.03.* INPUT FILE ------------------------------------\n")
        f.write(f"Generated by csf_to_openfast.py v{VERSION} from: {yaml_path}\n")

        f.write("---------------------- SIMULATION CONTROL -------------------------------\n")
        w(f, "False",      "Echo",       "Echo input data to <RootName>.ech (flag)")
        w(f, "3",          "Method",     "Integration method {1: RK4, 2: AB4, or 3: ABM4} (-)")
        w(f, '"DEFAULT"',  "DT",         'Integration time step (s) [or "DEFAULT"]')

        f.write("---------------------- DEGREES OF FREEDOM -------------------------------\n")
        w(f, "False", "FlapDOF1",  "First flapwise blade mode DOF (flag)")
        w(f, "False", "FlapDOF2",  "Second flapwise blade mode DOF (flag)")
        w(f, "False", "EdgeDOF",   "First edgewise blade mode DOF (flag)")
        w(f, "False", "PitchDOF",  "Blade pitch DOF (flag)")
        w(f, "False", "TeetDOF",   "Rotor-teeter DOF (flag)")
        w(f, "False", "DrTrDOF",   "Drivetrain rotational-flexibility DOF (flag)")
        w(f, "False", "GenDOF",    "Generator DOF (flag)")
        w(f, "False", "YawDOF",    "Yaw DOF (flag)")
        w(f, "True", "TwFADOF1",  "Tower 1st fore-aft bending mode DOF (flag)")
        w(f, "False", "TwFADOF2",  "Tower 2nd fore-aft bending mode DOF (flag)")
        w(f, "True", "TwSSDOF1",  "Tower 1st side-to-side bending mode DOF (flag)")
        w(f, "False", "TwSSDOF2",  "Tower 2nd side-to-side bending mode DOF (flag)")
        w(f, "False", "PtfmSgDOF", "Platform horizontal surge translation DOF (flag)")
        w(f, "False", "PtfmSwDOF", "Platform horizontal sway translation DOF (flag)")
        w(f, "False", "PtfmHvDOF", "Platform vertical heave translation DOF (flag)")
        w(f, "False", "PtfmRDOF",  "Platform roll tilt rotation DOF (flag)")
        w(f, "False", "PtfmPDOF",  "Platform pitch tilt rotation DOF (flag)")
        w(f, "False", "PtfmYDOF",  "Platform yaw rotation DOF (flag)")

        f.write("---------------------- INITIAL CONDITIONS -------------------------------\n")
        w(f, "0.0", "OoPDefl",   "Initial out-of-plane blade-tip displacement (m)")
        w(f, "0.0", "IPDefl",    "Initial in-plane blade-tip deflection (m)")
        w(f, "0.0", "BlPitch(1)","Blade 1 initial pitch angle (deg)")
        w(f, "0.0", "BlPitch(2)","Blade 2 initial pitch angle (deg)")
        w(f, "0.0", "BlPitch(3)","Blade 3 initial pitch angle (deg)")
        w(f, "0.0", "TeetDefl",  "Initial teeter angle (deg)")
        w(f, "0.0", "Azimuth",   "Initial azimuth angle for blade 1 (deg)")
        w(f, "0.0", "RotSpeed",  "Initial rotor speed (rpm)")
        w(f, "0.0", "NacYaw",    "Initial nacelle-yaw angle (deg)")
        w(f, "0.01", "TTDspFA",   "Initial fore-aft tower-top displacement (m)")
        w(f, "0.0", "TTDspSS",   "Initial side-to-side tower-top displacement (m)")
        w(f, "0.0", "PtfmSurge", "Initial platform surge displacement (m)")
        w(f, "0.0", "PtfmSway",  "Initial platform sway displacement (m)")
        w(f, "0.0", "PtfmHeave", "Initial platform heave displacement (m)")
        w(f, "0.0", "PtfmRoll",  "Initial platform roll angle (deg)")
        w(f, "0.0", "PtfmPitch", "Initial platform pitch angle (deg)")
        w(f, "0.0", "PtfmYaw",   "Initial platform yaw angle (deg)")

        f.write("---------------------- TURBINE CONFIGURATION ----------------------------\n")
        w(f, "3",                     "NumBl",     "Number of blades (-)")
        w(f, f"{tip_rad:.4f}",        "TipRad",    "Distance from rotor apex to blade tip (m)")
        w(f, f"{rna['hub_rad']:.4f}", "HubRad",    "Distance from rotor apex to blade root (m)")
        w(f, "0.0",                   "PreCone(1)","Blade 1 cone angle (deg)")
        w(f, "0.0",                   "PreCone(2)","Blade 2 cone angle (deg)")
        w(f, "0.0",                   "PreCone(3)","Blade 3 cone angle (deg)")
        w(f, "0.0",                   "HubCM",     "Distance from rotor apex to hub mass CM (m)")
        w(f, "0.0",                   "UndSling",  "Undersling length (m)")
        w(f, "0.0",                   "Delta3",    "Delta-3 angle for teetering rotors (deg)")
        w(f, "0.0",                   "AzimB1Up",  "Azimuth value for blade 1 pointing up (deg)")
        w(f, f"{rna['overhang']:.4f}","OverHang",  "Downwind distance from yaw axis to rotor apex (m)")
        w(f, "0.0",                   "ShftGagL",  "Distance from rotor apex to shaft strain gages (m)")
        w(f, "0.0",                   "ShftTilt",  "Rotor shaft tilt angle (deg)")
        w(f, f"{rna['cm_x']:.4f}",    "NacCMxn",   "Downwind distance from tower-top to nacelle CM (m)")
        w(f, "0.0",                   "NacCMyn",   "Lateral distance from tower-top to nacelle CM (m)")
        w(f, f"{rna['cm_z']:.4f}",    "NacCMzn",   "Vertical distance from tower-top to nacelle CM (m)")
        w(f, "0.0",                   "NcIMUxn",   "Downwind distance from tower-top to nacelle IMU (m)")
        w(f, "0.0",                   "NcIMUyn",   "Lateral distance from tower-top to nacelle IMU (m)")
        w(f, "0.0",                   "NcIMUzn",   "Vertical distance from tower-top to nacelle IMU (m)")
        w(f, "0.0",                   "Twr2Shft",  "Vertical distance from tower-top to rotor shaft (m)")
        w(f, f"{H:.4f}",              "TowerHt",   "Height of tower above ground level (m)")
        w(f, "0.0",                   "TowerBsHt", "Height of tower base above ground level (m)")
        w(f, "0.0",                   "PtfmCMxt",  "Downwind distance from reference to platform CM (m)")
        w(f, "0.0",                   "PtfmCMyt",  "Lateral distance from reference to platform CM (m)")
        w(f, "0.0",                   "PtfmCMzt",  "Vertical distance from reference to platform CM (m)")
        w(f, "0.0",                   "PtfmRefxt", "Downwind distance from reference origin to platform reference point (m)")
        w(f, "0.0",                   "PtfmRefyt", "Lateral distance from reference origin to platform reference point (m)")
        w(f, "0.0",                   "PtfmRefzt", "Vertical distance from reference origin to platform reference point (m)")

        f.write("---------------------- MASS AND INERTIA ---------------------------------\n")
        w(f, "0.0",                  "TipMass(1)",    "Tip-brake mass, blade 1 (kg)")
        w(f, "0.0",                  "TipMass(2)",    "Tip-brake mass, blade 2 (kg)")
        w(f, "0.0",                  "TipMass(3)",    "Tip-brake mass, blade 3 (kg)")
        w(f, "0.0",                  "PBrIner(1)",    "Pitch bearing inertia, blade 1 (kg m^2)")
        w(f, "0.0",                  "PBrIner(2)",    "Pitch bearing inertia, blade 2 (kg m^2)")
        w(f, "0.0",                  "PBrIner(3)",    "Pitch bearing inertia, blade 3 (kg m^2)")
        w(f, "0.0",                  "BlPIner(1)",    "Blade pitch inertia, blade 1 (kg m^2)")
        w(f, "0.0",                  "BlPIner(2)",    "Blade pitch inertia, blade 2 (kg m^2)")
        w(f, "0.0",                  "BlPIner(3)",    "Blade pitch inertia, blade 3 (kg m^2)")
        w(f, "0.0",                  "HubMass",       "Hub mass (kg)")
        w(f, "0.0",                  "HubIner",       "Hub inertia about rotor axis (kg m^2)")
        w(f, "0.0",                  "HubIner_Teet",  "Hub inertia about teeter axis (kg m^2)")
        w(f, "0.0",                  "GenIner",       "Generator inertia about HSS (kg m^2)")
        w(f, f"{rna['mass']:.6f}",   "NacMass",       "Nacelle mass (kg)")
        w(f, f"{rna['Izz']:.6E}",    "NacYIner",      "Nacelle inertia about yaw axis (kg m^2)")
        w(f, "0.0",                  "YawBrMass",     "Yaw bearing mass (kg)")
        w(f, "0.0",                  "PtfmMass",      "Platform mass (kg)")
        w(f, "0.0",                  "PtfmRIner",     "Platform roll inertia about platform CM (kg m^2)")
        w(f, "0.0",                  "PtfmPIner",     "Platform pitch inertia about platform CM (kg m^2)")
        w(f, "0.0",                  "PtfmYIner",     "Platform yaw inertia about platform CM (kg m^2)")
        w(f, "0.0",                  "PtfmXYIner",    "Platform xy product of inertia about platform CM (kg m^2)")
        w(f, "0.0",                  "PtfmYZIner",    "Platform yz product of inertia about platform CM (kg m^2)")
        w(f, "0.0",                  "PtfmXZIner",    "Platform xz product of inertia about platform CM (kg m^2)")

        f.write("---------------------- BLADE --------------------------------------------\n")
        w(f, "17",             "BldNodes",   "Number of blade nodes used for analysis (-)")
        w(f, f'"{bld_name}"',  "BldFile(1)", "Name of file containing properties for blade 1")
        w(f, f'"{bld_name}"',  "BldFile(2)", "Name of file containing properties for blade 2")
        w(f, f'"{bld_name}"',  "BldFile(3)", "Name of file containing properties for blade 3")

        f.write("---------------------- ROTOR-TEETER -------------------------------------\n")
        w(f, "0",   "TeetMod",   "Rotor-teeter spring/damper model (switch)")
        w(f, "0.0", "TeetDmpP",  "Rotor-teeter damper position (deg)")
        w(f, "0.0", "TeetDmp",   "Rotor-teeter damping constant (N-m/(rad/s))")
        w(f, "0.0", "TeetCDmp",  "Rotor-teeter Coulomb-damping moment (N-m)")
        w(f, "0.0", "TeetSStP",  "Rotor-teeter soft-stop position (deg)")
        w(f, "0.0", "TeetHStP",  "Rotor-teeter hard-stop position (deg)")
        w(f, "0.0", "TeetSSSp",  "Rotor-teeter soft-stop spring constant (N-m/rad)")
        w(f, "0.0", "TeetHSSp",  "Rotor-teeter hard-stop spring constant (N-m/rad)")

        f.write("---------------------- YAW FRICTION -------------------------------------\n")
        w(f, "0",   "YawFrctMod","Yaw-friction model (switch)")
        w(f, "300", "M_CSmax",   "Maximum static Coulomb friction torque (N-m)")
        w(f, "0",   "M_FCSmax",  "Maximum static Coulomb friction torque proportional to shear force (N-m)")
        w(f, "0",   "M_MCSmax",  "Maximum static Coulomb friction torque proportional to bending moment (N-m)")
        w(f, "40",  "M_CD",      "Dynamic Coulomb friction moment (N-m)")
        w(f, "0",   "M_FCD",     "Dynamic Coulomb friction moment proportional to shear force (N-m)")
        w(f, "0",   "M_MCD",     "Dynamic Coulomb friction moment proportional to bending moment (N-m)")
        w(f, "0",   "sig_v",     "Linear viscous friction coefficient (N-m/(rad/s))")
        w(f, "0",   "sig_v2",    "Quadratic viscous friction coefficient (N-m/(rad/s)^2)")
        w(f, "0",   "OmgCut",    "Yaw angular velocity cutoff (rad/s)")

        f.write("---------------------- DRIVETRAIN ----------------------------------------\n")
        w(f, "100.0", "GBoxEff",  "Gearbox efficiency (%)")
        w(f, "1.0",   "GBRatio",  "Gearbox ratio (-)")
        w(f, "0.0",   "DTTorSpr", "Drivetrain torsional spring (N-m/rad)")
        w(f, "0.0",   "DTTorDmp", "Drivetrain torsional damper (N-m/(rad/s))")

        f.write("---------------------- FURLING -------------------------------------------\n")
        w(f, "False",     "Furling",  "Read additional furling properties (flag)")
        w(f, '"unused"',  "FurlFile", "Name of file containing furling properties")

        f.write("---------------------- TOWER --------------------------------------------\n")
        w(f, "20",             "TwrNodes", "Number of tower nodes used for analysis (-)")
        w(f, f'"{twr_name}"',  "TwrFile",  "Name of file containing tower properties")

        f.write("---------------------- OUTPUT -------------------------------------------\n")
        w(f, "True",      "SumPrint", "Print summary data to <RootName>.sum (flag)")
        w(f, "1",         "OutFile",  "Output switch")
        w(f, "True",      "TabDelim", "Tab-delimited output (flag)")
        w(f, '"G0"',      "OutFmt",   "Format for tabular output")
        w(f, "0.0",       "TStart",   "Time to begin tabular output (s)")
        w(f, "1",         "DecFact",  "Decimation factor for tabular output (-)")
        w(f, "0",         "NTwGages", "Number of tower nodes with strain gages (-)")
        w(f, "0",         "TwrGagNd", "Tower node IDs for strain gages (-)")
        w(f, "0",         "NBlGages", "Number of blade nodes with strain gages (-)")
        w(f, "0",         "BldGagNd", "Blade node IDs for strain gages (-)")
        f.write("                OutList         - The next line(s) contains a list of output parameters\n")
        f.write('"TwrBsMxt"\n')
        f.write('"TwrBsMyt"\n')
        f.write("END\n")

        f.write("---------------------- NODE OUTPUTS -------------------------------------\n")
        w(f, "0",  "BldNd_BladesOut", "Blades to output for node channels")
        w(f, "99", "BldNd_BlOutNd",   "Blade nodes to output for node channels")
        f.write("                OutList         - The next line(s) contains a list of node output parameters\n")
        f.write("END\n")

    print(f"  Method = 3   DT = DEFAULT")
    print(f"  TowerHt = {H:.3f} m   TowerBsHt = 0.0 m")
    print(f"  NacMass = {rna['mass']:.0f} kg   NacYIner = {rna['Izz']:.3E} kg*m2")


def write_main_fst(
    outfile: str,
    ed_file: str,
    tmax: float,
    dt: float,
    yaml_path: str,
) -> None:
    """Write Main.fst aligned to MinimalExample architecture with CompSub=0."""
    step(6, f"Writing Main.fst: {outfile}")

    ed_name = os.path.basename(ed_file)

    with open(outfile, "w", encoding="utf-8") as f:
        f.write("---------- OpenFAST INPUT FILE -----------------------------------------------\n")
        f.write(f"Generated by csf_to_openfast.py v{VERSION} - MinimalExample-style case. Source: {yaml_path}\n")

        f.write("---------------------- SIMULATION CONTROL --------------------------------------\n")
        f.write("False         Echo            - Echo input data to <RootName>.ech (flag)\n")
        f.write('"FATAL"       AbortLevel      - Error level when simulation should abort (string) {"WARNING", "SEVERE", "FATAL"}\n')
        f.write(f"{tmax:11g}   TMax            - Total run time (s)\n")
        f.write(f"{dt:11g}   DT              - Recommended module time step (s)\n")
        f.write("          3   ModCoupling     - Module coupling method (switch) {1=loose; 2=tight with fixed Jacobian updates (DT_UJac); 3=tight with automatic Jacobian updates}\n")
        f.write("          2   InterpOrder     - Interpolation order for input/output time history (-) {1=linear, 2=quadratic}\n")
        f.write("          0   NumCrctn        - Number of correction iterations (-) {0=explicit calculation, i.e., no corrections}\n")
        f.write("        0.0   RhoInf          - Numerical damping parameter for tight coupling generalized-alpha integrator (-) [0.0 to 1.0]\n")
        f.write("       1e-4   ConvTol         - Convergence iteration error tolerance for tight coupling generalized alpha integrator (-)\n")
        f.write("          6   MaxConvIter     - Maximum number of convergence iterations for tight coupling generalized alpha integrator (-)\n")
        f.write("        1.5   DT_UJac         - Time between calls to get Jacobians (s)\n")
        f.write("      1E+06   UJacSclFact     - Scaling factor used in Jacobians (-)\n")

        f.write("---------------------- FEATURE SWITCHES AND FLAGS ------------------------------\n")
        f.write("          1   NRotors         - Number of rotors in turbine (-)\n")
        f.write("          1   CompElast       - Compute structural dynamics (switch) {1=ElastoDyn; 2=ElastoDyn + BeamDyn for blades; 3=Simplified ElastoDyn}\n")
        f.write("          0   CompInflow      - Compute inflow wind velocities (switch) {0=still air; 1=InflowWind; 2=external from ExtInflow}\n")
        f.write("          0   CompAero        - Compute aerodynamic loads (switch) {0=None; 1=AeroDisk; 2=AeroDyn; 3=ExtLoads}\n")
        f.write("          0   CompServo       - Compute control and electrical-drive dynamics (switch) {0=None; 1=ServoDyn}\n")
        f.write("          0   CompSeaSt       - Compute sea state information (switch) {0=None; 1=SeaState}\n")
        f.write("          0   CompHydro       - Compute hydrodynamic loads (switch) {0=None; 1=HydroDyn}\n")
        f.write("          0   CompSub         - Compute sub-structural dynamics (switch) {0=None; 1=SubDyn; 2=External Platform MCKF}\n")
        f.write("          0   CompMooring     - Compute mooring system (switch) {0=None; 1=MAP++; 2=FEAMooring; 3=MoorDyn; 4=OrcaFlex}\n")
        f.write("          0   CompIce         - Compute ice loads (switch) {0=None; 1=IceFloe; 2=IceDyn}\n")
        f.write("          0   CompSoil        - Compute soil-structural dynamics (switch) {0=None; 1=SoilDyn}\n")
        f.write("          0   MHK             - MHK turbine type (switch) {0=Not an MHK turbine; 1=Fixed MHK turbine; 2=Floating MHK turbine}\n")
        f.write("          F   MirrorRotor     - Flag to reverse rotor rotation direction [1 to NRotors] {F=Normal, T=Mirror}\n")

        f.write("---------------------- ENVIRONMENTAL CONDITIONS --------------------------------\n")
        f.write("9.80665                Gravity       - Gravitational acceleration (m/s^2)\n")
        f.write("1.225                  AirDens       - Air density (kg/m^3)\n")
        f.write("0                      WtrDens       - Water density (kg/m^3)\n")
        f.write("1.464e-05              KinVisc       - Kinematic viscosity of working fluid (m^2/s)\n")
        f.write("335                    SpdSound      - Speed of sound in working fluid (m/s)\n")
        f.write("103500                 Patm          - Atmospheric pressure (Pa) [used only for an MHK turbine cavitation check]\n")
        f.write("1700                   Pvap          - Vapour pressure of working fluid (Pa) [used only for an MHK turbine cavitation check]\n")
        f.write("0                      WtrDpth       - Water depth (m)\n")
        f.write("0                      MSL2SWL       - Offset between still-water level and mean sea level (m) [positive upward]\n")

        f.write("---------------------- INPUT FILES ---------------------------------------------\n")
        f.write(f'"{ed_name}"      EDFile          - Name of file containing ElastoDyn input parameters (quoted string)\n')
        f.write('"unused"      BDBldFile(1)    - Name of file containing BeamDyn input parameters for blade 1 (quoted string)\n')
        f.write('"unused"      BDBldFile(2)    - Name of file containing BeamDyn input parameters for blade 2 (quoted string)\n')
        f.write('"unused"      BDBldFile(3)    - Name of file containing BeamDyn input parameters for blade 3 (quoted string)\n')
        f.write('"unused"      InflowFile      - Name of file containing inflow wind input parameters (quoted string)\n')
        f.write('"unused"      AeroFile        - Name of file containing aerodynamic input parameters (quoted string)\n')
        f.write('"unused"      ServoFile       - Name of file containing control and electrical-drive input parameters (quoted string)\n')
        f.write('"unused"      SeaStFile       - Name of file containing sea state input parameters (quoted string)\n')
        f.write('"unused"      HydroFile       - Name of file containing hydrodynamic input parameters (quoted string)\n')
        f.write('"unused"      SubFile         - Name of file containing sub-structural input parameters (quoted string)\n')
        f.write('"unused"      MooringFile     - Name of file containing mooring system input parameters (quoted string)\n')
        f.write('"unused"      IceFile         - Name of file containing ice input parameters (quoted string)\n')
        f.write('"unused"      SoilFile        - Name of the file containing the SoilDyn input parameters (quoted string)\n')

        f.write("---------------------- OUTPUT --------------------------------------------------\n")
        f.write("True          SumPrint        - Print summary data to <RootName>.sum (flag)\n")
        f.write("          1   SttsTime        - Amount of time between screen status messages (s)\n")
        f.write("      99999   ChkptTime       - Amount of time between creating checkpoint files for potential restart (s)\n")
        f.write(f"{dt:11g}     DT_Out          - Time step for tabular output (s) (or \"default\")\n")
        f.write("          0   TStart          - Time to begin tabular output (s)\n")
        f.write("          3   OutFileFmt      - Format for tabular (time-marching) output file (switch) {1: text file [<RootName>.out], 2: binary file [<RootName>.outb], 3: both}\n")
        f.write("True          TabDelim        - Use tab delimiters in text tabular output file? (flag) {uses spaces if false}\n")
        f.write('"G0"          OutFmt          - Format used for text tabular output, excluding the time channel.  Resulting field should be 10 characters. (quoted string)\n')

        f.write("---------------------- LINEARIZATION -------------------------------------------\n")
        f.write("False         Linearize       - Linearization analysis (flag)\n")
        f.write("False         CalcSteady      - Calculate a steady-state periodic operating point before linearization? [unused if Linearize=False] (flag)\n")
        f.write("          3   TrimCase        - Controller parameter to be trimmed {1:yaw; 2:torque; 3:pitch} [used only if CalcSteady=True] (-)\n")
        f.write("      0.001   TrimTol         - Tolerance for the rotational speed convergence [used only if CalcSteady=True] (-)\n")
        f.write("       0.01   TrimGain        - Proportional gain for the rotational speed error (>0) [used only if CalcSteady=True] (rad/(rad/s) for yaw or pitch; Nm/(rad/s) for torque)\n")
        f.write("          0   Twr_Kdmp        - Damping factor for the tower [used only if CalcSteady=True] (N/(m/s))\n")
        f.write("          0   Bld_Kdmp        - Damping factor for the blades [used only if CalcSteady=True] (N/(m/s))\n")
        f.write("          1   NLinTimes       - Number of times to linearize (-) [>=1] [unused if Linearize=False]\n")
        f.write("          0   LinTimes        - List of times at which to linearize (s) [1 to NLinTimes] [unused if Linearize=False]\n")
        f.write("          1   LinInputs       - Inputs included in linearization (switch) {0=none; 1=standard; 2=all module inputs (debug)} [unused if Linearize=False]\n")
        f.write("          1   LinOutputs      - Outputs included in linearization (switch) {0=none; 1=from OutList(s); 2=all module outputs (debug)} [unused if Linearize=False]\n")
        f.write("False         LinOutJac       - Include full Jacobians in linearization output (for debug) (flag) [unused if Linearize=False; used only if LinInputs=LinOutputs=2]\n")
        f.write("False         LinOutMod       - Write module-level linearization output files in addition to output for full system? (flag) [unused if Linearize=False]\n")

        f.write("---------------------- VISUALIZATION ------------------------------------------\n")
        f.write("          0   WrVTK           - VTK visualization data output: (switch) {0=none; 1=initialization data only; 2=animation}\n")
        f.write("          1   VTK_type        - Type of VTK visualization data: (switch) {1=surfaces; 2=basic meshes (lines/points); 3=all meshes (debug)} [unused if WrVTK=0]\n")
        f.write("false         VTK_fields      - Write mesh fields to VTK data files? (flag) {true/false} [unused if WrVTK=0]\n")
        f.write("         15   VTK_fps         - Frame rate for VTK output (frames per second){will use closest integer multiple of DT} [used only if WrVTK=2]\n")

    print("  Main.fst written with CompSub = 0")


# =============================================================================
# Optional: run OpenFAST
# =============================================================================

def run_openfast(exe: str, fst_file: str) -> None:
    step(7, f"Running OpenFAST: {exe}  {fst_file}")
    subprocess.run(
        [str(Path(exe).resolve()), str(Path(fst_file).resolve())],
        check=True,
    )


# =============================================================================
# argparse
# =============================================================================

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Generate OpenFAST minimal input files from a CSF geometry YAML (no SubDyn).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("yaml", help="CSF geometry YAML file")

    mat = p.add_argument_group("material")
    mat.add_argument("--E",   type=float, required=True, help="Young's modulus [Pa]")
    mat.add_argument("--rho", type=float, required=True, help="Density [kg/m3]")

    disc = p.add_argument_group("tower discretization")
    disc.add_argument("--n-stations", type=int, required=True, help="Number of tower stations for ElastoDyn_Tower.dat")

    rna = p.add_argument_group("RNA (Rotor-Nacelle Assembly)")
    rna.add_argument("--rna-mass",  type=float, required=True, help="Total RNA mass [kg]")
    rna.add_argument("--rna-ixx",   type=float, required=True, help="Side-to-side inertia [kg m^2] (stored only for logging)")
    rna.add_argument("--rna-iyy",   type=float, required=True, help="Fore-aft inertia [kg m^2] (stored only for logging)")
    rna.add_argument("--rna-izz",   type=float, required=True, help="Yaw inertia [kg m^2]")
    rna.add_argument("--rna-cm-x",  type=float, required=True, help="CM downstream offset from tower-top [m]")
    rna.add_argument("--rna-cm-z",  type=float, required=True, help="CM vertical offset from tower-top [m]")
    rna.add_argument("--hub-rad",   type=float, required=True, help="Hub radius [m]")
    rna.add_argument("--overhang",  type=float, required=True, help="Rotor apex offset from yaw axis [m]")

    sim = p.add_argument_group("simulation")
    sim.add_argument("--tmax", type=float, required=True, help="Simulation duration [s]")
    sim.add_argument("--dt",   type=float, required=True, help="Time step [s]")

    p.add_argument("--out",          type=str, default=None, help="Output filename stem (default: YAML stem)")
    p.add_argument("--openfast-exe", type=str, default=None, help="Path to OpenFAST executable (optional)")

    return p.parse_args()


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    print()
    print(f"[csf_to_openfast v{VERSION}]  CSF -> OpenFAST minimal pipeline")
    print("=" * 65)

    args = parse_args()

    yaml_path = args.yaml
    out_dir   = os.getcwd()
    stem      = args.out if args.out else os.path.splitext(os.path.basename(yaml_path))[0]
    base      = stem

    twr_file = os.path.join(out_dir, base + "_ElastoDyn_Tower.dat")
    ed_file  = os.path.join(out_dir, base + "_ElastoDyn.dat")
    bld_file = os.path.join(out_dir, base + "_ElastoDyn_Blade.dat")
    fst_file = os.path.join(out_dir, base + "_Main.fst")

    rna = {
        "mass":     args.rna_mass,
        "Ixx":      args.rna_ixx,
        "Iyy":      args.rna_iyy,
        "Izz":      args.rna_izz,
        "cm_x":     args.rna_cm_x,
        "cm_z":     args.rna_cm_z,
        "hub_rad":  args.hub_rad,
        "overhang": args.overhang,
    }

    try:
        field, z0, z1 = load_csf(yaml_path)
        props = compute_properties(field, z0, z1, args.n_stations)
        write_elastodyn_tower(twr_file, props, z0, z1, args.E, args.rho, yaml_path)
        write_elastodyn_blade(bld_file, args.hub_rad, yaml_path)
        write_elastodyn(ed_file, twr_file, bld_file, z0, z1, rna, yaml_path)
        write_main_fst(fst_file, ed_file, args.tmax, args.dt, yaml_path)
    except Exception as exc:
        print()
        print(f"[csf_to_openfast v{VERSION}]  ERROR: {exc}")
        raise

    print()
    print("=" * 65)
    print(f"[csf_to_openfast v{VERSION}]  Generated files:")
    for f in (twr_file, ed_file, bld_file, fst_file):
        print(f"  {f}")
    print()

    if args.openfast_exe:
        run_openfast(args.openfast_exe, fst_file)


if __name__ == "__main__":
    main()
