import argparse
import math
import yaml


# =========================
# YAML output helpers
# =========================
class CleanDumper(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True


class Point(list):
    pass


def _repr_point(dumper, data):
    return dumper.represent_sequence("tag:yaml.org,2002:seq", list(data), flow_style=True)


CleanDumper.add_representer(Point, _repr_point)


# =========================
# Geometry helpers
# =========================
def signed_area(vertices):
    if len(vertices) < 3:
        return 0.0
    a = 0.0
    n = len(vertices)
    for i in range(n):
        x1, y1 = vertices[i]
        x2, y2 = vertices[(i + 1) % n]
        a += x1 * y2 - x2 * y1
    return 0.5 * a


def close_loop(points):
    if not points:
        return points
    x0, y0 = points[0]
    xN, yN = points[-1]
    if x0 != xN or y0 != yN:
        points = points + [[x0, y0]]
    return points


def to_points(vertices):
    return [Point([float(x), float(y)]) for x, y in vertices]


def parse_bool(value):
    if isinstance(value, bool):
        return value
    s = str(value).strip().lower()
    if s in ("true", "1", "yes", "y", "on"):
        return True
    if s in ("false", "0", "no", "n", "off"):
        return False
    raise argparse.ArgumentTypeError(f"Invalid boolean value: {value}")


def rotate_points(points, cx, cy, angle_deg):
    a = math.radians(angle_deg)
    ca, sa = math.cos(a), math.sin(a)
    out = []
    for x, y in points:
        dx, dy = x - cx, y - cy
        out.append([cx + ca * dx - sa * dy, cy + sa * dx + ca * dy])
    return out


def rounded_rect_loop(cx, cy, dx, dy, R, n, ccw=True):
    # The same generator is used for both base and head.
    hx, hy = dx / 2.0, dy / 2.0
    Lh = max(dx - 2.0 * R, 0.0)
    Lv = max(dy - 2.0 * R, 0.0)
    La = 0.5 * math.pi * R
    seg = [Lv / 2.0, La, Lh, La, Lv, La, Lh, La, Lv / 2.0]
    P = sum(seg)
    cum = [0.0]
    for L in seg:
        cum.append(cum[-1] + L)

    xL, xR, yB, yT = cx - hx, cx + hx, cy - hy, cy + hy

    def at_s(s):
        i = 0
        while i < len(seg) - 1 and s >= cum[i + 1]:
            i += 1
        ds, Li = s - cum[i], seg[i]
        if i == 0:
            return [xR, cy + (yT - R - cy) * (ds / Li if Li > 0 else 0)]
        if i == 1:
            a = (ds / Li if Li > 0 else 0) * (math.pi / 2.0)
            return [xR - R + R * math.cos(a), yT - R + R * math.sin(a)]
        if i == 2:
            return [xR - R - Lh * (ds / Li if Li > 0 else 0), yT]
        if i == 3:
            a = math.pi / 2.0 + (ds / Li if Li > 0 else 0) * (math.pi / 2.0)
            return [xL + R + R * math.cos(a), yT - R + R * math.sin(a)]
        if i == 4:
            return [xL, yT - R - Lv * (ds / Li if Li > 0 else 0)]
        if i == 5:
            a = math.pi + (ds / Li if Li > 0 else 0) * (math.pi / 2.0)
            return [xL + R + R * math.cos(a), yB + R + R * math.sin(a)]
        if i == 6:
            return [xL + R + Lh * (ds / Li if Li > 0 else 0), yB]
        if i == 7:
            a = 1.5 * math.pi + (ds / Li if Li > 0 else 0) * (math.pi / 2.0)
            return [xR - R + R * math.cos(a), yB + R + R * math.sin(a)]
        return [xR, yB + R + (cy - (yB + R)) * (ds / Li if Li > 0 else 0)]

    pts = [at_s((k / n) * P) for k in range(n)]
    return pts if ccw else list(reversed(pts))


def make_square(cx, cy, area):
    side = math.sqrt(area)
    h = side / 2.0
    return [[cx - h, cy - h], [cx + h, cy - h], [cx + h, cy + h], [cx - h, cy + h]]


def ensure_ccw(points):
    v = close_loop(points)
    if signed_area(v) < 0.0:
        v = list(reversed(v))
    return v


def build_single_cell_vertices(outer_loop, inner_loop):
    # The inner loop is expected in single-polygon orientation.
    return close_loop(outer_loop) + close_loop(inner_loop)


def offset_rounded_rect_params(cx, cy, dx, dy, R, offset):
    dx2 = dx - 2.0 * offset
    dy2 = dy - 2.0 * offset
    R2 = R - offset
    if dx2 <= 0.0 or dy2 <= 0.0 or R2 < 0.0:
        raise ValueError(
            f"Invalid rounded-rectangle offset: dx={dx}, dy={dy}, R={R}, offset={offset}"
        )
    return cx, cy, dx2, dy2, R2


def expand_rounded_rect_params(cx, cy, dx, dy, R, offset):
    dx2 = dx + 2.0 * offset
    dy2 = dy + 2.0 * offset
    R2 = R + offset
    if dx2 <= 0.0 or dy2 <= 0.0 or R2 < 0.0:
        raise ValueError(
            f"Invalid rounded-rectangle expansion: dx={dx}, dy={dy}, R={R}, offset={offset}"
        )
    return cx, cy, dx2, dy2, R2


def build_rebar_centers_on_two_rows(
    cx,
    cy,
    outer_dx,
    outer_dy,
    outer_R,
    inner_dx,
    inner_dy,
    inner_R,
    n_row1,
    n_row2,
    d_row1_outer,
    d_row2_inner,
):
    # Row 1 is generated by offsetting inward from the outer contour.
    row1 = []
    # Row 2 is generated by expanding outward from the inner contour.
    row2 = []

    if n_row1 > 0:
        p = offset_rounded_rect_params(cx, cy, outer_dx, outer_dy, outer_R, d_row1_outer)
        row1 = rounded_rect_loop(*p, n_row1)

    if n_row2 > 0:
        p = expand_rounded_rect_params(cx, cy, inner_dx, inner_dy, inner_R, d_row2_inner)
        row2 = rounded_rect_loop(*p, n_row2)

    return row1, row2


def build_section_geometry(
    cx,
    cy,
    dx,
    dy,
    R,
    tg,
    N,
    n_bars_row1,
    n_bars_row2,
    dist_row1_outer,
    dist_row2_inner,
    twist_deg=0.0,
):
    # The inner contour is obtained by a geometric inward offset.
    inner_dx = dx - 2.0 * tg
    inner_dy = dy - 2.0 * tg
    inner_R = max(R - tg, 0.0)

    # Build the outer loop and the inner CCW loop with the same algorithm.
    outer = rounded_rect_loop(cx, cy, dx, dy, R, N, ccw=True)
    inner_ccw = rounded_rect_loop(cx, cy, inner_dx, inner_dy, inner_R, N, ccw=True)

    # The single-polygon encoding uses the inner loop with reversed traversal.
    inner_single = list(reversed(inner_ccw))
    main_single = build_single_cell_vertices(outer, inner_single)

    # Rebar rows follow the same external and internal guide contours.
    row1_centers, row2_centers = build_rebar_centers_on_two_rows(
        cx,
        cy,
        dx,
        dy,
        R,
        inner_dx,
        inner_dy,
        inner_R,
        n_bars_row1,
        n_bars_row2,
        dist_row1_outer,
        dist_row2_inner,
    )

    # Twist is optional and is applied to the whole head package consistently.
    if twist_deg != 0.0:
        outer = rotate_points(outer, cx, cy, twist_deg)
        inner_ccw = rotate_points(inner_ccw, cx, cy, twist_deg)
        inner_single = rotate_points(inner_single, cx, cy, twist_deg)
        row1_centers = rotate_points(row1_centers, cx, cy, twist_deg)
        row2_centers = rotate_points(row2_centers, cx, cy, twist_deg)

        # Rebuild the single-polygon representation from normalized loops.
        outer = ensure_ccw(outer)
        inner_ccw = ensure_ccw(inner_ccw)
        inner_single = list(reversed(inner_ccw))
        main_single = build_single_cell_vertices(outer, inner_single)

    return {
        "outer": outer,
        "inner_ccw": inner_ccw,
        "main_single": main_single,
        "row1_centers": row1_centers,
        "row2_centers": row2_centers,
    }


def build_section_dict(z, section_geom, name, t_val, args):
    polys = {}

    if args.singlepolygon:
        poly_name = f"cell_{name}@cell" if t_val == 0 else f"cell_{name}@cell@t={t_val}"
        polys[poly_name] = {"weight": 1.0, "vertices": to_points(section_geom["main_single"])}
    else:
        outer_name = f"cell_{name}_outer" if t_val == 0 else f"cell_{name}_outer@t={t_val}"
        inner_name = f"cell_{name}_inner" if t_val == 0 else f"cell_{name}_inner@t={t_val}"

        # In dual-polygon mode both loops are exported as CCW polygons.
        polys[outer_name] = {"weight": 1.0, "vertices": to_points(ensure_ccw(section_geom["outer"]))}
        polys[inner_name] = {"weight": 0.0, "vertices": to_points(ensure_ccw(section_geom["inner_ccw"]))}

    # Row 1 bars are written using the row-specific equivalent square area.
    for i, (cx_bar, cy_bar) in enumerate(section_geom["row1_centers"], start=1):
        polys[f"rebar_row1_{i}"] = {
            "weight": args.rebar_weight,
            "vertices": to_points(make_square(cx_bar, cy_bar, args.area_bar_row1)),
        }

    # Row 2 bars are written independently to preserve the original naming/output scheme.
    for i, (cx_bar, cy_bar) in enumerate(section_geom["row2_centers"], start=1):
        polys[f"rebar_row2_{i}"] = {
            "weight": args.rebar_weight,
            "vertices": to_points(make_square(cx_bar, cy_bar, args.area_bar_row2)),
        }

    return {"z": float(z), "polygons": polys}


def _pair_entry(s0_name, s1_name, law):
    # Each weight-law entry is emitted as one compact string in the YAML list.
    return f"{s0_name},{s1_name}: {law}"


def build_weight_laws(args):
    # Collect optional weight laws and append them at the end of the CSF block.
    weight_laws = []

    # A row law is expanded into one entry per rebar pair so the output stays explicit.
   
    if args.bars_row1_law and args.n_bars_row1 > 0:
        for i in range(1, args.n_bars_row1 + 1):
            
            name = f"rebar_row1_{i}"
            weight_laws.append(_pair_entry(name, name, args.bars_row1_law))

    if args.bars_row2_law and args.n_bars_row2 > 0:
        for i in range(1, args.n_bars_row2 + 1):
            name = f"rebar_row2_{i}"
            weight_laws.append(_pair_entry(name, name, args.bars_row2_law))

    # The tower shell law is applied only to the real shell polygon.
    # In dual-polygon mode the inner hole stays geometric void (weight 0) and
    # therefore no law is written for the inner polygon.
    if args.singlepolygon:
        shell_s0_name = "cell_base@cell" if args.s0_t_cell == 0 else f"cell_base@cell@t={args.s0_t_cell}"
        shell_s1_name = "cell_head@cell" if args.s1_t_cell == 0 else f"cell_head@cell@t={args.s1_t_cell}"
    else:
        shell_s0_name = "cell_base_outer" if args.s0_t_cell == 0 else f"cell_base_outer@t={args.s0_t_cell}"
        shell_s1_name = "cell_head_outer" if args.s1_t_cell == 0 else f"cell_head_outer@t={args.s1_t_cell}"

    # The current v2 interface accepts two shell-law arguments. If both are
    # provided they must match, because the requested export format uses a
    # single pair entry for the shell across S0 and S1.
    shell_laws = [law for law in (args.s0_law, args.s1_law) if law]
    if len(shell_laws) == 2 and shell_laws[0] != shell_laws[1]:
        raise ValueError(
            "s0_law and s1_law must match in writegeometry_rio_v2.py, because "
            "the shell is exported as one paired weight-law entry."
        )
    shell_law = shell_laws[0] if shell_laws else ""
    if shell_law:
        
        weight_laws.append(_pair_entry(shell_s0_name, shell_s1_name, shell_law))

    return weight_laws


# =========================
# Main builder logic
# =========================
def build_geometry(args):
    # Both sections use the same parameter family and the same builder.
    s0 = build_section_geometry(
        cx=args.s0_x,
        cy=args.s0_y,
        dx=args.s0_dx,
        dy=args.s0_dy,
        R=args.s0_R,
        tg=args.s0_tg,
        N=args.N,
        n_bars_row1=args.n_bars_row1,
        n_bars_row2=args.n_bars_row2,
        dist_row1_outer=args.dist_row1_outer,
        dist_row2_inner=args.dist_row2_inner,
        twist_deg=0.0,
    )

    s1 = build_section_geometry(
        cx=args.s1_x,
        cy=args.s1_y,
        dx=args.s1_dx,
        dy=args.s1_dy,
        R=args.s1_R,
        tg=args.s1_tg,
        N=args.N,
        n_bars_row1=args.n_bars_row1,
        n_bars_row2=args.n_bars_row2,
        dist_row1_outer=args.dist_row1_outer,
        dist_row2_inner=args.dist_row2_inner,
        twist_deg=args.twist_deg,
    )

    data = {
        "CSF": {
            "sections": {
                "S0": build_section_dict(args.z0, s0, "base", args.s0_t_cell, args),
                "S1": build_section_dict(args.z1, s1, "head", args.s1_t_cell, args),
            }
        }
    }

    weight_laws = build_weight_laws(args)
    if weight_laws:
        data["CSF"]["weight_laws"] = weight_laws
    #print(f"DEBUG {weight_laws}")
    return data


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Build a CSF geometry YAML with optional paired weight-law export."
    )

    # Longitudinal coordinates
    parser.add_argument("--z0", type=float, required=True)
    parser.add_argument("--z1", type=float, required=True)

    # Section S0 geometry.
    # Legacy option names are kept as aliases for backward compatibility.
    parser.add_argument("--s0-t-cell", "--tf-cell", dest="s0_t_cell", type=float, required=True)
    parser.add_argument("--s0-tg", "--tg-base", dest="s0_tg", type=float, required=True)
    parser.add_argument("--s0-x", "--cx", dest="s0_x", type=float, required=True)
    parser.add_argument("--s0-y", "--cy", dest="s0_y", type=float, required=True)
    parser.add_argument("--s0-dx", "--bdx", dest="s0_dx", type=float, required=True)
    parser.add_argument("--s0-dy", "--bdy", dest="s0_dy", type=float, required=True)
    parser.add_argument("--s0-R", "--bR", dest="s0_R", type=float, required=True)

    # Section S1 geometry.
    # Legacy option names are kept as aliases for backward compatibility.
    parser.add_argument("--s1-t-cell", "--th-cell", dest="s1_t_cell", type=float, required=True)
    parser.add_argument("--s1-tg", "--tg-head", dest="s1_tg", type=float, required=True)
    parser.add_argument("--s1-x", "--rcx", dest="s1_x", type=float, required=True)
    parser.add_argument("--s1-y", "--rcy", dest="s1_y", type=float, required=True)
    parser.add_argument("--s1-dx", "--rdx", dest="s1_dx", type=float, required=True)
    parser.add_argument("--s1-dy", "--rdy", dest="s1_dy", type=float, required=True)
    parser.add_argument("--s1-R", "--R", dest="s1_R", type=float, required=True)

    # Twist and discretization
    parser.add_argument("--twist-deg", type=float, default=0.0)
    parser.add_argument("--N", type=int, required=True)
    parser.add_argument("--singlepolygon", type=parse_bool, required=True)

    # Rebar rows
    parser.add_argument("--n-bars-row1", type=int, required=True)
    parser.add_argument("--n-bars-row2", type=int, required=True)
    parser.add_argument("--area-bar-row1", type=float, required=True)
    parser.add_argument("--area-bar-row2", type=float, required=True)
    parser.add_argument("--dist-row1-outer", type=float, required=True)
    parser.add_argument("--dist-row2-inner", type=float, required=True)
    parser.add_argument("--rebar-weight", type=float, required=True)

    # Optional weight laws appended after the geometry block.
    parser.add_argument("--bars-row1-law", type=str, default="")
    parser.add_argument("--bars-row2-law", type=str, default="")
    parser.add_argument("--s0-law", type=str, default="")
    parser.add_argument("--s1-law", type=str, default="")

    # Output
    parser.add_argument("--out", type=str, default="softwarex_geometry.yaml")

    args = parser.parse_args()

    if args.z1 <= args.z0:
        raise ValueError("z1 must be > z0.")
    if args.n_bars_row1 < 0 or args.n_bars_row2 < 0:
        raise ValueError("The number of bars per row must be >= 0.")
    if args.area_bar_row1 <= 0.0 or args.area_bar_row2 <= 0.0:
        raise ValueError("The single-bar areas must be > 0.")
    if args.dist_row1_outer < 0.0 or args.dist_row2_inner < 0.0:
        raise ValueError("The row distances must be >= 0.")

    geom = build_geometry(args)
    with open(args.out, "w", encoding="utf-8") as f:
        yaml.dump(geom, f, Dumper=CleanDumper, sort_keys=False, default_flow_style=False)

    print(f"File generated successfully: {args.out}")
