"""
CSF-SP @cell verification example.

Purpose
-------
This script verifies the CSF -> csf_sp -> sectionproperties path for a
slit-encoded @cell polygon.

The verification is split into two checks:

1) Geometric consistency
   - CSF reference model: ordinary geometry with:
       outer polygon, weight = 1.0
       inner polygon, weight = 0.0
   - sectionproperties model: generated by csf_sp from one slit-encoded @cell.
   - Compared quantities:
       A, Cx, Cy, Ix, Iy, Ixy, Ip, I1, I2, rx, ry

2) Torsional consistency
   - CSF @cell model: one slit-encoded @cell polygon.
   - sectionproperties model: same csf_sp conversion.
   - Compared quantity:
       CSF J_sv_cell against sectionproperties e.j

The torsional comparison is not expected to be exact at machine precision:
CSF uses the @cell Saint-Venant thin-walled/Bredt-type path, while
sectionproperties computes the torsion constant numerically.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple

import matplotlib.pyplot as plt

from csf import (
    ContinuousSectionField,
    Polygon,
    Pt,
    Section,
    section_full_analysis,
)
from csf.utils.csf_sp import analyse


Z0 = 0.0
Z1 = 10.0

DEFAULT_MESH_SIZE = 1.0e-4
DEFAULT_Z_STATIONS = (0.0, 5.0, 10.0)

GEOM_ABS_TOL = 1.0e-9
GEOM_REL_TOL = 1.0e-7

TORSION_ABS_TOL = 1.0e-8
TORSION_REL_TOL = 1.0e-1


# ---------------------------------------------------------------------------
# Numeric helpers.
# ---------------------------------------------------------------------------
def _safe_rel_delta(delta: float, reference: float) -> float:
    """Return a relative delta, using zero only when the reference is zero."""
    if abs(reference) == 0.0:
        return 0.0
    return delta / reference


def _principal_from_inertia(ix: float, iy: float, ixy: float) -> Tuple[float, float]:
    """Compute principal second moments from centroidal Ix, Iy and Ixy."""
    avg = 0.5 * (ix + iy)
    rad = math.sqrt((0.5 * (ix - iy)) ** 2 + ixy**2)
    return avg + rad, avg - rad


def _format_float(value: float) -> str:
    """Format one numeric value for compact text and Markdown reports."""
    return f"{value:.12e}"


def _extract_first(value):
    """Return the first component when CSF returns a tuple-valued property."""
    if isinstance(value, tuple):
        return value[0]
    return value


def _get_sp_ej(sec_sp) -> float:
    """Return sectionproperties composite torsion stiffness e.j."""
    if hasattr(sec_sp, "get_ej"):
        return float(sec_sp.get_ej())

    raise AttributeError(
        "sectionproperties object does not expose get_ej(); "
        "cannot extract composite torsion result e.j."
    )


def _comparison_rows(
    csf_result: Dict[str, float],
    sp_result: Dict[str, float],
    keys: Sequence[str],
    abs_tol: float,
    rel_tol: float,
) -> List[Tuple[str, float, float, float, float, bool]]:
    """Build comparison rows: name, CSF, SP, delta, relative delta, pass flag."""
    rows = []

    for key in keys:
        csf_value = float(csf_result[key])
        sp_value = float(sp_result[key])
        delta = csf_value - sp_value
        rel_delta = _safe_rel_delta(delta, sp_value)
        pass_flag = abs(delta) <= abs_tol or abs(rel_delta) <= rel_tol
        rows.append((key, csf_value, sp_value, delta, rel_delta, pass_flag))

    return rows


def _rows_to_text(title: str, rows: Sequence[Tuple[str, float, float, float, float, bool]]) -> str:
    """Render comparison rows as a fixed-width text table."""
    lines = [
        "",
        title,
        f"{'Property':<14} {'CSF':>20} {'SP':>20} {'Delta':>20} {'RelDelta':>14} {'OK':>5}",
        "-" * 101,
    ]

    for name, csf_value, sp_value, delta, rel_delta, pass_flag in rows:
        lines.append(
            f"{name:<14} "
            f"{csf_value:>20.12e} "
            f"{sp_value:>20.12e} "
            f"{delta:>20.12e} "
            f"{rel_delta:>14.6e} "
            f"{str(pass_flag):>5}"
        )

    return "\n".join(lines)


def _rows_to_markdown(
    title: str,
    rows: Sequence[Tuple[str, float, float, float, float, bool]],
) -> str:
    """Render comparison rows as a Markdown table."""
    lines = [
        f"### {title}",
        "",
        "| Property | CSF | SP | Delta | RelDelta | OK |",
        "|---|---:|---:|---:|---:|:---:|",
    ]

    for name, csf_value, sp_value, delta, rel_delta, pass_flag in rows:
        lines.append(
            "| "
            f"{name} | "
            f"{_format_float(csf_value)} | "
            f"{_format_float(sp_value)} | "
            f"{_format_float(delta)} | "
            f"{rel_delta:.6e} | "
            f"{'yes' if pass_flag else 'no'} |"
        )

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Geometry definition.
# ---------------------------------------------------------------------------
def _polygon(vertices: Sequence[Pt], weight: float, name: str) -> Polygon:
    """Create one CSF polygon."""
    return Polygon(vertices=tuple(vertices), weight=weight, name=name)


def _make_slit_encoded_cell(outer_vertices: Sequence[Pt], inner_tail: Sequence[Pt]) -> Tuple[Pt, ...]:
    """Build one slit-encoded @cell polygon.

    Encoding rule:
    - outer loop vertices;
    - repeated first outer vertex;
    - inner loop tail;
    - repeated first inner vertex.
    """
    return (
        *outer_vertices,
        outer_vertices[0],
        *inner_tail,
        inner_tail[0],
    )


def build_fields() -> Tuple[ContinuousSectionField, ContinuousSectionField]:
    """Build ordinary reference field and slit-encoded @cell field."""

    # S0 outer boundary: irregular CCW loop.
    outer_s0 = (
        Pt(-0.14, -0.16),
        Pt( 0.08, -0.18),
        Pt( 0.15, -0.08),
        Pt( 0.13,  0.12),
        Pt( 0.02,  0.18),
        Pt(-0.12,  0.14),
        Pt(-0.17,  0.02),
    )

    # S1 outer boundary: same vertex count, slightly tapered and warped.
    outer_s1 = (
        Pt(-0.12, -0.14),
        Pt( 0.07, -0.155),
        Pt( 0.13, -0.07),
        Pt( 0.11,  0.105),
        Pt( 0.015, 0.155),
        Pt(-0.105, 0.12),
        Pt(-0.145, 0.015),
    )

    # Inner loop tail for slit-encoded @cell.
    # This ordering is opposite to the outer loop orientation.
    inner_tail_s0 = (
        Pt(-0.09, -0.10),
        Pt(-0.11,  0.03),
        Pt(-0.05,  0.10),
        Pt( 0.05,  0.11),
        Pt( 0.10,  0.02),
        Pt( 0.08, -0.09),
        Pt(-0.02, -0.13),
    )

    inner_tail_s1 = (
        Pt(-0.075, -0.085),
        Pt(-0.095,  0.025),
        Pt(-0.045,  0.085),
        Pt( 0.045,  0.095),
        Pt( 0.085,  0.018),
        Pt( 0.068, -0.075),
        Pt(-0.018, -0.110),
    )

    # Ordinary CSF geometry uses regular standalone loops.
    # The inner loop is reversed so it is a regular CCW polygon.
    inner_geom_s0 = tuple(reversed(inner_tail_s0))
    inner_geom_s1 = tuple(reversed(inner_tail_s1))

    s0_geom = Section(
        polygons=(
            _polygon(outer_s0, 1.0, "outer"),
            _polygon(inner_geom_s0, 0.0, "inner_void"),
        ),
        z=Z0,
    )

    s1_geom = Section(
        polygons=(
            _polygon(outer_s1, 1.0, "outer"),
            _polygon(inner_geom_s1, 0.0, "inner_void"),
        ),
        z=Z1,
    )

    ordinary_field = ContinuousSectionField(section0=s0_geom, section1=s1_geom)

    cell_s0 = _polygon(
        _make_slit_encoded_cell(outer_s0, inner_tail_s0),
        1.0,
        "irregular_cell@cell",
    )

    cell_s1 = _polygon(
        _make_slit_encoded_cell(outer_s1, inner_tail_s1),
        1.0,
        "irregular_cell@cell",
    )

    s0_cell = Section(polygons=(cell_s0,), z=Z0)
    s1_cell = Section(polygons=(cell_s1,), z=Z1)

    cell_field = ContinuousSectionField(section0=s0_cell, section1=s1_cell)

    return ordinary_field, cell_field


# ---------------------------------------------------------------------------
# Result extraction.
# ---------------------------------------------------------------------------
def extract_sp_results(sec_sp) -> Dict[str, float]:
    """Extract sectionproperties composite results and derived quantities."""
    area = sec_sp.get_ea()
    cx, cy = sec_sp.get_c()
    ix, iy, ixy = sec_sp.get_eic()

    ip = ix + iy
    i1, i2 = _principal_from_inertia(ix, iy, ixy)
    rx = math.sqrt(ix / area)
    ry = math.sqrt(iy / area)
    ej = _get_sp_ej(sec_sp)

    return {
        "A": area,
        "Cx": cx,
        "Cy": cy,
        "Ix": ix,
        "Iy": iy,
        "Ixy": ixy,
        "Ip": ip,
        "I1": i1,
        "I2": i2,
        "rx": rx,
        "ry": ry,
        "e.j": ej,
    }


def extract_csf_results(field: ContinuousSectionField, z: float) -> Dict[str, float]:
    """Run CSF section analysis at one station."""
    return section_full_analysis(field.section(z))


# ---------------------------------------------------------------------------
# Main verification routine.
# ---------------------------------------------------------------------------
def run_verification(
    z_stations: Iterable[float],
    mesh_size: float,
    report_path: Path,
    plot: bool,
) -> bool:
    """Run the full @cell verification and write a Markdown report."""
    ordinary_field, cell_field = build_fields()

    geometry_keys = ("A", "Cx", "Cy", "Ix", "Iy", "Ixy", "Ip", "I1", "I2", "rx", "ry")

    all_geometry_rows = []
    all_torsion_rows = []
    text_blocks = []

    markdown_blocks = [
        "# CSF-SP @cell Verification Report",
        "",
        "## Model",
        "",
        "This benchmark verifies a slit-encoded `@cell` polygon converted through "
        "`csf_sp` into a `sectionproperties` model.",
        "",
        "Two CSF fields are used:",
        "",
        "1. an ordinary reference field with `outer weight = 1.0` and "
        "`inner weight = 0.0`, used for geometric quantities;",
        "2. a slit-encoded `@cell` field, used for `csf_sp` conversion and "
        "`J_sv_cell` evaluation.",
        "",
        "The geometric comparison is expected to match at numerical precision. "
        "The torsional comparison checks consistency between CSF `J_sv_cell` and "
        "`sectionproperties` `e.j`, using a looser tolerance because the two "
        "paths use different torsion formulations.",
        "",
        f"Geometry absolute tolerance: `{GEOM_ABS_TOL:.1e}`",
        f"Geometry relative tolerance: `{GEOM_REL_TOL:.1e}`",
        f"Torsion absolute tolerance: `{TORSION_ABS_TOL:.1e}`",
        f"Torsion relative tolerance: `{TORSION_REL_TOL:.1e}`",
        f"Mesh size: `{mesh_size:.6g}`",
        "",
    ]

    z_stations = tuple(z_stations)

    for z in z_stations:
        csf_geom = extract_csf_results(ordinary_field, z)
        csf_cell = extract_csf_results(cell_field, z)

        sec_sp = analyse(cell_field, z=z, mesh=mesh_size)

        if plot:
            ax = sec_sp.geometry.plot_geometry(
                labels=("points", "facets", "control_points"),
                cp=True,
            )
            ax.set_title(f"@cell sectionproperties geometry at z = {z}")
            ax.set_aspect("equal", adjustable="box")
            plt.show(block=True)

            ax = sec_sp.plot_mesh(materials=False)
            ax.set_title(f"@cell sectionproperties mesh at z = {z}")
            ax.set_aspect("equal", adjustable="box")
            plt.show(block=True)

        sp_result = extract_sp_results(sec_sp)

        geometry_rows = _comparison_rows(
            csf_geom,
            sp_result,
            geometry_keys,
            GEOM_ABS_TOL,
            GEOM_REL_TOL,
        )

        csf_j_cell = float(_extract_first(csf_cell["J_sv_cell"]))
        torsion_rows = _comparison_rows(
            {"J_sv_cell": csf_j_cell},
            {"J_sv_cell": sp_result["e.j"]},
            ("J_sv_cell",),
            TORSION_ABS_TOL,
            TORSION_REL_TOL,
        )

        all_geometry_rows.extend((z, *row) for row in geometry_rows)
        all_torsion_rows.extend((z, *row) for row in torsion_rows)

        geom_title = f"Geometric check: CSF ordinary reference vs csf_sp @cell at z = {z}"
        torsion_title = f"Torsion check: CSF J_sv_cell vs sectionproperties e.j at z = {z}"

        text_blocks.append(_rows_to_text(geom_title, geometry_rows))
        text_blocks.append(_rows_to_text(torsion_title, torsion_rows))
        text_blocks.append("")
        text_blocks.append("Expected @cell torsion flags")
        text_blocks.append(f"J_sv_cell: {csf_cell['J_sv_cell']}")
        text_blocks.append(f"J_sv_wall: {csf_cell['J_sv_wall']}")

        markdown_blocks.append(_rows_to_markdown(geom_title, geometry_rows))
        markdown_blocks.append("")
        markdown_blocks.append(_rows_to_markdown(torsion_title, torsion_rows))
        markdown_blocks.append("")
        markdown_blocks.append("Expected `@cell` torsion flags:")
        markdown_blocks.append("")
        markdown_blocks.append(f"- `J_sv_cell`: `{csf_cell['J_sv_cell']}`")
        markdown_blocks.append(f"- `J_sv_wall`: `{csf_cell['J_sv_wall']}`")
        markdown_blocks.append("")

    max_geom_abs = max(abs(row[4]) for row in all_geometry_rows)
    max_geom_rel = max(abs(row[5]) for row in all_geometry_rows)
    max_torsion_abs = max(abs(row[4]) for row in all_torsion_rows)
    max_torsion_rel = max(abs(row[5]) for row in all_torsion_rows)

    failed_geometry = [row for row in all_geometry_rows if not row[6]]
    failed_torsion = [row for row in all_torsion_rows if not row[6]]

    passed = len(failed_geometry) == 0 and len(failed_torsion) == 0

    summary = [
        "",
        "GLOBAL SUMMARY",
        "==============",
        f"stations checked: {len(z_stations)}",
        f"geometry properties per station: {len(geometry_keys)}",
        f"maximum geometry absolute delta: {max_geom_abs:.12e}",
        f"maximum geometry relative delta: {max_geom_rel:.6e}",
        f"maximum torsion absolute delta: {max_torsion_abs:.12e}",
        f"maximum torsion relative delta: {max_torsion_rel:.6e}",
        f"overall status: {'PASS' if passed else 'FAIL'}",
    ]

    text_blocks.extend(summary)

    markdown_blocks.extend(
        [
            "## Global summary",
            "",
            f"- Stations checked: `{len(z_stations)}`",
            f"- Geometry properties per station: `{len(geometry_keys)}`",
            f"- Maximum geometry absolute delta: `{max_geom_abs:.12e}`",
            f"- Maximum geometry relative delta: `{max_geom_rel:.6e}`",
            f"- Maximum torsion absolute delta: `{max_torsion_abs:.12e}`",
            f"- Maximum torsion relative delta: `{max_torsion_rel:.6e}`",
            f"- Overall status: `{'PASS' if passed else 'FAIL'}`",
            "",
        ]
    )

    if failed_geometry or failed_torsion:
        markdown_blocks.append("## Failed rows")
        markdown_blocks.append("")
        markdown_blocks.append("| Group | z | Property | Delta | RelDelta |")
        markdown_blocks.append("|---|---:|---|---:|---:|")

        for z, name, _csf_value, _sp_value, delta, rel_delta, _pass_flag in failed_geometry:
            markdown_blocks.append(
                f"| geometry | {z:.6g} | {name} | {_format_float(delta)} | {rel_delta:.6e} |"
            )

        for z, name, _csf_value, _sp_value, delta, rel_delta, _pass_flag in failed_torsion:
            markdown_blocks.append(
                f"| torsion | {z:.6g} | {name} | {_format_float(delta)} | {rel_delta:.6e} |"
            )

        markdown_blocks.append("")

    report_path.write_text("\n".join(markdown_blocks), encoding="utf-8")

    print("\n".join(text_blocks))
    print(f"\nMarkdown report written to: {report_path}")

    return passed


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Run a CSF-SP @cell verification case."
    )
    parser.add_argument(
        "--mesh",
        type=float,
        default=DEFAULT_MESH_SIZE,
        help=f"sectionproperties mesh size. Default: {DEFAULT_MESH_SIZE}",
    )
    parser.add_argument(
        "--z",
        type=float,
        nargs="*",
        default=list(DEFAULT_Z_STATIONS),
        help="z stations to check. Default: 0.0 5.0 10.0",
    )
    parser.add_argument(
        "--report",
        type=Path,
        default=Path("csf_sp_cell_verification_report.md"),
        help="Markdown report output path.",
    )
    parser.add_argument(
        "--plot",
        action="store_true",
        help="Show sectionproperties geometry and mesh plots at each station.",
    )
    return parser.parse_args()


def main() -> int:
    """Program entry point."""
    args = parse_args()

    passed = run_verification(
        z_stations=tuple(args.z),
        mesh_size=args.mesh,
        report_path=args.report,
        plot=args.plot,
    )

    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
